server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:user-service;DB_CLOSE_DELAY=-1
    username: sa
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations: classpath:init.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop


springdoc:
  swagger-ui:
    enabled: true
