server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:user-service;DB_CLOSE_DELAY=-1
    username: sa
  h2:
    console:
      enabled: true

  #  init:
  #   data-locations: classpath:input.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    #sql:
springdoc:
  swagger-ui:
    enabled: true